version: "3.8"

services:
  codex:
    build: .
    image: codex-cli:latest
    environment:
      - OPENAI_API_KEY    # or use a .env file
    tty: true
    stdin_open: true
    # keep container alive
    command: tail -f /dev/null